name: hi_paw
description: >-
  Aplicativo Flutter com autenticação Firebase e arquitetura limpa
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.0.0
  go_router: ^14.2.7
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  video_player: ^2.9.1
  equatable: ^2.0.5
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - lib/l10n/
    - images/

flutter_native_splash:
  color: '#FFFFFF'
  image: images/splash_screen.jpg
  android_12:
    image: images/splash_screen.jpg
    color: '#FFFFFF'
